import { Document, Page, Text, View } from '@react-pdf/renderer';

import { styles } from '@/features/analyze-fit/pdf/styles';

import { PDFCompanyHealth } from './components/PDFCompanyHealth';
import { PDFCultureIntel } from './components/PDFCultureIntel';
import { PDFInterviewPrep } from './components/PDFInterviewPrep';

export type DeepResearchReportData = {
  companyHealth?: {
    status?: string;
    summary?: string;
    redFlags?: string[];
  };
  cultureIntel?: {
    keywords?: string[];
    managerVibe?: string;
    engineeringCulture?: string;
  };
  interviewPrepGuide?: {
    interviewFormat?: {
      style?: string;
      description?: string;
      evidence?: string;
    };
    skillGapCrashCourses?: {
      topic?: string;
      companyContext?: string;
      studyTip?: string;
    }[];
    strategicQuestions?: {
      question?: string;
      context?: string;
    }[];
  };
};

type DeepResearchDocumentProps = {
  data: DeepResearchReportData;
};

export function DeepResearchDocument({ data }: DeepResearchDocumentProps) {
  const generatedDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <View>
            <Text style={styles.headerTitle}>ROLE REPORT AI</Text>
            <Text style={styles.headerSubtitle}>Deep Research Report</Text>
          </View>
          <View>
            <Text style={styles.headerDate}>{generatedDate}</Text>
          </View>
        </View>

        {/* Company Health */}
        <PDFCompanyHealth
          status={data.companyHealth?.status}
          summary={data.companyHealth?.summary}
          redFlags={data.companyHealth?.redFlags}
        />

        {/* Cultural Fingerprint */}
        <PDFCultureIntel
          keywords={data.cultureIntel?.keywords}
          managerVibe={data.cultureIntel?.managerVibe}
          engineeringCulture={data.cultureIntel?.engineeringCulture}
        />

        {/* Interview Prep */}
        <PDFInterviewPrep
          interviewFormat={data.interviewPrepGuide?.interviewFormat}
          skillGapCrashCourses={data.interviewPrepGuide?.skillGapCrashCourses}
          strategicQuestions={data.interviewPrepGuide?.strategicQuestions}
        />

        {/* Footer */}
        <View style={styles.footer} fixed>
          <Text>Generated by Role Report AI</Text>
          <Text>rolereport.ai</Text>
        </View>
      </Page>
    </Document>
  );
}
