import { Document, Image, Page, Text, View } from '@react-pdf/renderer';

import { PDFLearningPriorities } from './components/pdf-learning-priorities.component';
import { PDFMatchScore } from './components/pdf-match-score.component';
import { PDFOptimizations } from './components/pdf-optimizations.component';
import { PDFSkillAssessment } from './components/pdf-skill-assessment.component';
import { colors, styles } from './styles.util';

export type AnalysisReportData = {
  suitabilityAssessment?: {
    suitabilityScore?: number;
    bottomLine?: string;
    keyStrengths?: string[];
    criticalGaps?: string[];
    criteriaBreakdown?: {
      coreSkillsMatch?: { score: number; reasoning?: string };
      experienceRelevance?: { score: number; reasoning?: string };
      skillGapsSeverity?: { score: number; reasoning?: string };
      transferableSkills?: { score: number; reasoning?: string };
      overallPotential?: { score: number; reasoning?: string };
    };
  };
  skillAssessment?: {
    skills?: (
      | {
          skillName?: string;
          status?: string;
          importance?: string;
          reasoning?: string;
        }
      | undefined
    )[];
  };
  resumeOptimizations?: {
    plan?: (
      | {
          title?: string;
          priority?: string;
          category?: string;
          description?: string;
          estimatedEffort?: string;
          example?: any;
        }
      | undefined
    )[];
  };
  learningPriorities?: {
    plan?: (
      | {
          title?: string;
          priority?: string;
          category?: string;
          description?: string;
          estimatedTime?: string;
          resource?: string;
          outcome?: string;
        }
      | undefined
    )[];
  };
  chartImage?: string;
};

type AnalysisReportDocumentProps = {
  data: AnalysisReportData;
};

export function AnalysisReportDocument(props: AnalysisReportDocumentProps) {
  const { data } = props;

  const generatedDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <View>
            <Text style={styles.headerTitle}>ROLE REPORT AI</Text>
            <Text style={styles.headerSubtitle}>Fit Analysis Report</Text>
          </View>
          <View>
            <Text style={styles.headerDate}>{generatedDate}</Text>
          </View>
        </View>

        {/* Match Score Section */}
        <PDFMatchScore
          suitabilityScore={data.suitabilityAssessment?.suitabilityScore}
          bottomLine={data.suitabilityAssessment?.bottomLine}
          keyStrengths={data.suitabilityAssessment?.keyStrengths}
          criticalGaps={data.suitabilityAssessment?.criticalGaps}
          criteriaBreakdown={data.suitabilityAssessment?.criteriaBreakdown}
        />

        {/* Radar Chart Image */}
        {data.chartImage && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Skills Analysis</Text>
            <View style={{ alignItems: 'center' }}>
              <Image src={data.chartImage} style={styles.chartImage} />
              <View style={[styles.row, { justifyContent: 'center', gap: 24, marginTop: 8 }]}>
                <View style={[styles.row, { alignItems: 'center', gap: 4 }]}>
                  <View
                    style={{
                      width: 12,
                      height: 12,
                      backgroundColor: colors.primary,
                      borderRadius: 2,
                    }}
                  />
                  <Text style={{ fontSize: 8, color: colors.mediumGray }}>Candidate Level</Text>
                </View>
                <View style={[styles.row, { alignItems: 'center', gap: 4 }]}>
                  <View
                    style={{ width: 12, height: 12, backgroundColor: '#3B82F6', borderRadius: 2 }}
                  />
                  <Text style={{ fontSize: 8, color: colors.mediumGray }}>Required Level</Text>
                </View>
              </View>
            </View>
          </View>
        )}

        {/* Skill Assessment */}
        <PDFSkillAssessment skills={data.skillAssessment?.skills} />

        {/* Footer */}
        <View style={styles.footer} fixed>
          <Text>Generated by Role Report AI</Text>
          <Text>rolereport.ai</Text>
        </View>
      </Page>

      {/* Second Page for Optimizations and Learning */}
      {(data.resumeOptimizations?.plan?.length || data.learningPriorities?.plan?.length) && (
        <Page size="A4" style={styles.page}>
          {/* Header (simplified for continuation) */}
          <View style={[styles.header, { marginBottom: 16 }]}>
            <View>
              <Text style={[styles.headerTitle, { fontSize: 14 }]}>ROLE REPORT AI</Text>
              <Text style={[styles.headerSubtitle, { fontSize: 10 }]}>
                Action Items & Learning Plan
              </Text>
            </View>
          </View>

          {/* Resume Optimizations */}
          <PDFOptimizations optimizations={data.resumeOptimizations?.plan} />

          {/* Learning Priorities */}
          <PDFLearningPriorities priorities={data.learningPriorities?.plan} />

          {/* Footer */}
          <View style={styles.footer} fixed>
            <Text>Generated by Role Report AI</Text>
            <Text>rolereport.ai</Text>
          </View>
        </Page>
      )}
    </Document>
  );
}
